import path from 'path';
import fs from 'fs/promises';

import { glob } from 'glob';
import { minify } from 'html-minifier-terser';

import { eleventyDirs } from '../eleventy.config.mjs';

export async function minifyHTML() {
	console.log('\n📦 Minifying HTML...\n');

	const { output } = eleventyDirs;
	const htmlFiles = await glob(`${output}/**/*.html`);

	if (htmlFiles.length === 0) {
		console.log('⚠️  HTML Minify: No HTML files found to process');
		return;
	}

	const options = {
		collapseBooleanAttributes: true,
		collapseWhitespace: true,
		conservativeCollapse: false,
		decodeEntities: true,
		html5: true,
		includeAutoGeneratedTags: false,
		minifyCSS: true,
		minifyJS: true,
		preserveLineBreaks: false,
		preventAttributesEscaping: true,
		removeAttributeQuotes: true,
		removeComments: true,
		removeEmptyAttributes: true,
		removeOptionalTags: false,
		removeRedundantAttributes: true,
		removeScriptTypeAttributes: true,
		removeStyleLinkTypeAttributes: true,
		sortAttributes: true,
		sortClassName: true,
		useShortDoctype: true,
	};

	let totalOriginalSize = 0;
	let totalMinifiedSize = 0;
	let successCount = 0;
	let errorCount = 0;
	const errors = [];

	for (const file of htmlFiles) {
		try {
			const html = await fs.readFile(file, 'utf-8');
			const originalSize = Buffer.byteLength(html, 'utf8');
			const minified = await minify(html, options);
			const minifiedSize = Buffer.byteLength(minified, 'utf8');

			await fs.writeFile(file, minified);

			totalOriginalSize += originalSize;
			totalMinifiedSize += minifiedSize;

			const savings = ((1 - minifiedSize / originalSize) * 100).toFixed(1);
			console.log(`✓ ${path.relative(output, file)} (${savings}% smaller)`);
			successCount++;
		} catch (error) {
			errorCount++;
			errors.push({
				file: path.relative(output, file),
				error: error.message,
			});
			console.error(`✗ ${path.relative(output, file)}: ${error.message}`);
		}
	}

	const totalSavings = (
		(1 - totalMinifiedSize / totalOriginalSize) *
		100
	).toFixed(1);
	console.log(
		`\n✓ HTML minified: ${successCount}/${htmlFiles.length} pages, ${totalSavings}% reduction (${(totalOriginalSize / 1024).toFixed(1)} KB → ${(totalMinifiedSize / 1024).toFixed(1)} KB)${errorCount > 0 ? `, ${errorCount} failed` : ''}\n`,
	);

	if (errorCount > 0) {
		console.error('\n❌ HTML Minification Errors:');
		errors.forEach(({ file, error }) => {
			console.error(`   ${file}: ${error}`);
		});
		console.error(
			'\nTip: Check if HTML is valid and properly formed. Invalid HTML can cause minification to fail.',
		);
		throw new Error(
			`HTML minification failed for ${errorCount} file(s). See errors above.`,
		);
	}
}
